### ISSUE TITLE
JSON.parse is not async

### ISSUE THREAD

**Issue by nelix** [Kikobeats/json-parse-async#1]
The main issue with this is that JSON.parse is blocking.

Via the fetch API you could (when present) make an async json api.
http://azimi.me/2015/07/30/non-blocking-async-json-parse.html

**Comment by Kikobeats** [comment]
Yes, it's true. The current implementation is based in delay the action in the event loop. I saw this solution the past week and could be a better solution. Can you make a PR of this?

**Comment by nelix** [comment]
PR is up!
