### ISSUE TITLE
How is this async?

### ISSUE THREAD

**Issue by YouriT** [Kikobeats/json-parse-async#12]
From your source, you don't seem to do anything async here. Your `JSON.parse` is in the main thread and does block the event loop.

**Comment by Kikobeats** [comment]
Not real async because parsing is a pure CPU function.

The only thing you can do is deferred the execution/response for the next tick. Exactly the thing this library does.

BTW, I think this library is outdated; Currently Please, check [json-future](https://github.com/Kikobeats/json-future) 😄
