### ISSUE TITLE
Is this shit not async?

### ISSUE THREAD

**Issue by gentlee** [Kikobeats/json-parse-async#4]
Does the dev is a stupid peace of shit and made sync method as promise or it is just me not understanding how it works?

**Comment by Kikobeats** [comment]
I think that this project is deprecated. Better use https://github.com/kikobeats/json-future#parseasyncinput-reviver-filename-cb.

Take in consideration the purpose here is providing a consistent async API, because not possible create a native async implementation.

PS: Don't be rude.

**Comment by Gentlee** [comment]
then you better write about that in description so that i don't need to look another one "async" implementation  of some stupid idiot.
